# Generated by Django 3.1.5 on 2021-01-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainCategory',
            new_name='Category',
        ),
    ]
