# Generated by Django 3.1.5 on 2021-01-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('has_sizes', models.BooleanField(blank=True, default=False, null=True)),
                ('image_url_1', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url_2', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
